name = "JuliaAstroDocs"
uuid = "5ba9df79-bc07-467f-bade-66a1d49082bd"

[deps]
ParallelTestRunner = "d3525ed8-44d0-4b2c-a655-542cee43accc"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
ParallelTestRunner = "2.0.1"
TypedTables = "1.4.6"
julia = "1.10"

[workspace]
projects = ["test", "docs"]
