name = "JuliaAstroDocs"
uuid = "5ba9df79-bc07-467f-bade-66a1d49082bd"

[workspace]
projects = ["test", "docs"]

[deps]
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
TypedTables = "1.4.6"
julia = "1.10"
