name: build

on:
  push:
    branches: [source]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - run: julia --project=. -e '
          using Pkg;
          Pkg.instantiate();'
      - run: julia --project=. make.jl
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
