name: Test JuliaAstro (dev)

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron:  '15 2 * * *' # 2:15 AM UTC every day

jobs:
  uses: ./github/workflows/CI.yml
  with:
    test_args: "--verbose release"
