name: Test JuliaAstro (release)

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron:  '15 2 * * *' # 2:15 AM UTC every day

jobs:
  test-release:
    uses: ./.github/workflows/CI.yml
    with:
      test_args: "--verbose packages_release"
