name: Build website
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron:  '15 2 * * *' # 2:15 AM UTC every day
jobs:
  docs:
    name: MultiDocumentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-docdeploy@v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dev-docs-cleanup:
    needs: docs
    name: dev docs cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2

      - name: Delete dev docs
        run: |
          git rm -rf ./Spectra/dev/
      - name: Push changes
        run: |
          git config user.name "Documenter.jl"
          git config user.email "documenter@juliadocs.github.io"
          git commit -m "delete dev docs"
          git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
          git push --force origin gh-pages-new:gh-pages
